### ISSUE TITLE
Feature request: categorize quests

### ISSUE THREAD

**Issue by mike-seagull** [need4swede/SideQuests#1]
Awesome project!
It would be helpful to be able to categorize quests with colors.

**Comment by lephtHanded** [comment]
or a tag?
#forTheWife

**Comment by need4swede** [comment]
I'll have to think about how, and if, I want to add additional organizational features. I want the app to remain 'simple' in its use. I'll play around with some new designs to see if anything clicks. I will close the request for now and might revisit it at a later date.

In the meantime, I've added one additional organizational feature - 'Group Objectives'.
It's a simple toggle that separates completed tasks from active ones. Along with the new sorting behaviors I've added, it should greatly help with keeping things neat.

Thank you for your ideas! Hope you enjoy the app
