### ISSUE TITLE
external facing issue

### ISSUE THREAD

**Issue by lephtHanded** [need4swede/SideQuests#3]
Hola, 
thanks for the great app!

i'm running this behind NPM and when ever i to go to `https://quests.doma.in`, the URL loads:
`https://quests.doma.in/login?next=http://quests.doma.in/` which gives me a 403 forbidden instead of the login page.

i've modified my bookmarks to just use `https://quests.doma.in/login` but thought you'd like to know.

**Comment by need4swede** [comment]
I've updated the authentication logic.
Please try the latest release (v1.1.5) and see if it works for you.
If using Docker, simply use the latest image.

**Comment by need4swede** [comment]
@lephtHanded are you still experiencing this issue?
