### ISSUE TITLE
How can I tell what version I have?

### ISSUE THREAD

**Issue by nebbishOne** [need4swede/SideQuests#4]
Hello, love this little app - thanks very much for it. I am running the Docker version and it's great but I don't know how to tell which version I have installed.

My compose file says:

`image: need4swede/sidequests:latest`

So I figure I am up to date rn, but is there someplace I can see the version, please?

Thanks!

**Comment by need4swede** [comment]
Hello,

That’s an excellent question!
I currently don’t have versions listed anywhere in the UI, but if you ‘docker compose down’ and remove the image and then install it again, you’re guaranteed to grab the latest image.

I am currently enjoying some family leave and have put my projects on the back burner. I’ll be tackling this app again soon and I’ll add visible versions into the UI in the next release.

Thank you for sharing your experience with me and I am delighted to hear that you enjoy my app! Really means a lot. If you have any further questions, please don’t hesitate to ask. Cheers!
